-- Production output fact.
-- Scope:
-- - One row per source production output line.
-- - Current primary source: "____(Hasan) Update Stok Produksi - Produksi (1).csv"
-- - Only rows with source record type "Produksi Harian" belong here.
-- - Internal return rows from the same source file must be loaded to a separate table.
--
-- Safe to rerun.

BEGIN;

CREATE TABLE IF NOT EXISTS public.fact_production_output (
    production_output_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_system text NOT NULL DEFAULT 'manual_spreadsheet',
    source_record_type text NOT NULL,

    production_date date NOT NULL,
    production_datetime timestamptz,

    product_id integer REFERENCES public.dim_product(product_id),
    product_sku_alias_id integer REFERENCES public.product_sku_alias(product_sku_alias_id),

    source_sku_code text,
    source_product_name text NOT NULL,

    quantity_produced numeric(18, 4) NOT NULL,
    unit text NOT NULL DEFAULT 'PCS',

    warehouse_id integer,
    source_warehouse_name text,

    source_from_raw text,
    source_box_raw text,

    source_file text NOT NULL,
    source_sheet text,
    source_row_number integer NOT NULL,
    raw_record_id text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_fact_production_output_record_type CHECK (
        source_record_type = 'Produksi Harian'
    ),
    CONSTRAINT ck_fact_production_output_quantity_non_negative CHECK (
        quantity_produced >= 0
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_production_output_raw_record
ON public.fact_production_output (source_system, raw_record_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_production_output_source_row
ON public.fact_production_output (
    source_system,
    source_file,
    source_row_number
);

CREATE INDEX IF NOT EXISTS idx_fact_production_output_date
ON public.fact_production_output (production_date);

CREATE INDEX IF NOT EXISTS idx_fact_production_output_product
ON public.fact_production_output (product_id);

CREATE INDEX IF NOT EXISTS idx_fact_production_output_sku_alias
ON public.fact_production_output (product_sku_alias_id);

CREATE INDEX IF NOT EXISTS idx_fact_production_output_source_sku
ON public.fact_production_output (source_sku_code);

CREATE INDEX IF NOT EXISTS idx_fact_production_output_warehouse
ON public.fact_production_output (warehouse_id);

COMMIT;
