-- Packaging purchase fact.
-- Scope:
-- - Legacy fact_packaging_purchase.csv exported from wellfarm_legacy.
-- - Packaging item resolution uses inventory_item_source_alias.
--
-- Grain:
-- - 1 row per source purchase line.
--
-- Safe to rerun.

BEGIN;

CREATE TABLE IF NOT EXISTS public.fact_packaging_purchase (
    packaging_purchase_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_system text NOT NULL DEFAULT 'legacy_wellfarm',

    supplier_id integer REFERENCES public.dim_supplier(supplier_id),
    inventory_item_id integer REFERENCES public.dim_inventory_item(inventory_item_id),

    source_purchase_id text NOT NULL,
    source_supplier_id text,
    supplier_match_method text,

    source_product_id text,
    source_packaging_name text NOT NULL,
    inventory_item_match_method text,

    ket_code text,
    po_number text,

    invoice_date date NOT NULL,
    received_date date,
    dp_date date,
    paid_date date,

    quantity numeric(18, 4) NOT NULL,
    unit text NOT NULL DEFAULT 'PCS',
    unit_price_excl_vat numeric(18, 2) NOT NULL,
    subtotal_amount numeric(18, 2) NOT NULL,
    dp_amount numeric(18, 2),

    source_file text NOT NULL,
    source_sheet text,
    source_row_number integer NOT NULL,
    raw_record_id text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_fact_packaging_purchase_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_fact_packaging_purchase_unit_price_non_negative CHECK (unit_price_excl_vat >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_packaging_purchase_raw_record
ON public.fact_packaging_purchase (source_system, raw_record_id);

CREATE INDEX IF NOT EXISTS idx_fact_packaging_purchase_invoice_date
ON public.fact_packaging_purchase (invoice_date);

CREATE INDEX IF NOT EXISTS idx_fact_packaging_purchase_received_date
ON public.fact_packaging_purchase (received_date);

CREATE INDEX IF NOT EXISTS idx_fact_packaging_purchase_supplier
ON public.fact_packaging_purchase (supplier_id);

CREATE INDEX IF NOT EXISTS idx_fact_packaging_purchase_inventory_item
ON public.fact_packaging_purchase (inventory_item_id);

CREATE INDEX IF NOT EXISTS idx_fact_packaging_purchase_source
ON public.fact_packaging_purchase (source_system, source_file);

COMMIT;
