-- Inventory stock movement fact.
-- Scope:
-- - Legacy fact_stock_out.csv exported from wellfarm_legacy.
-- - Current load covers stock-out / distribution movement only.
--
-- Grain:
-- - 1 row per source stock-out line.
--
-- Safe to rerun.

BEGIN;

CREATE TABLE IF NOT EXISTS public.fact_inventory_stock_movement (
    inventory_stock_movement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_system text NOT NULL DEFAULT 'legacy_wellfarm',
    movement_type text NOT NULL,
    movement_subtype text,
    movement_date date NOT NULL,

    product_id integer REFERENCES public.dim_product(product_id),
    product_sku_alias_id integer REFERENCES public.product_sku_alias(product_sku_alias_id),
    b2b_partner_id integer REFERENCES public.dim_b2b_partner(b2b_partner_id),

    source_stock_out_id text NOT NULL,
    source_product_id text,
    source_sku_code text,
    source_product_name text NOT NULL,
    product_match_method text,

    source_b2b_partner_id text,
    source_customer_name text,
    b2b_partner_match_method text,

    source_do_number text,
    source_invoice_number text,
    source_cargo_number text,
    source_expedisi text,

    quantity numeric(18, 4) NOT NULL,
    source_quantity_ordered numeric(18, 4),
    source_quantity_shipped numeric(18, 4),
    unit text NOT NULL DEFAULT 'PCS',

    source_file text NOT NULL,
    source_sheet text,
    source_row_number integer NOT NULL,
    raw_record_id text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_fact_inventory_stock_movement_type CHECK (
        movement_type IN ('stock_out')
    ),
    CONSTRAINT ck_fact_inventory_stock_movement_quantity_positive CHECK (
        quantity > 0
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_inventory_stock_movement_raw_record
ON public.fact_inventory_stock_movement (source_system, raw_record_id);

CREATE INDEX IF NOT EXISTS idx_fact_inventory_stock_movement_date
ON public.fact_inventory_stock_movement (movement_date);

CREATE INDEX IF NOT EXISTS idx_fact_inventory_stock_movement_type
ON public.fact_inventory_stock_movement (movement_type, movement_subtype);

CREATE INDEX IF NOT EXISTS idx_fact_inventory_stock_movement_product
ON public.fact_inventory_stock_movement (product_id);

CREATE INDEX IF NOT EXISTS idx_fact_inventory_stock_movement_sku_alias
ON public.fact_inventory_stock_movement (product_sku_alias_id);

CREATE INDEX IF NOT EXISTS idx_fact_inventory_stock_movement_partner
ON public.fact_inventory_stock_movement (b2b_partner_id);

CREATE INDEX IF NOT EXISTS idx_fact_inventory_stock_movement_source_doc
ON public.fact_inventory_stock_movement (source_do_number, source_invoice_number);

CREATE INDEX IF NOT EXISTS idx_fact_inventory_stock_movement_source
ON public.fact_inventory_stock_movement (source_system, source_file);

COMMIT;
