-- Internal stock return fact.
-- Scope:
-- - One row per internal return line from production/stock spreadsheet.
-- - Current primary source: "____(Hasan) Update Stok Produksi - Produksi (1).csv"
-- - Rows with source record type "Produksi Harian" do not belong here.
-- - Marketplace/customer returns remain in fact_sales_return/fact_sales_return_item.
--
-- Safe to rerun.

BEGIN;

CREATE TABLE IF NOT EXISTS public.fact_internal_stock_return (
    internal_stock_return_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_system text NOT NULL DEFAULT 'manual_spreadsheet',
    source_return_type text NOT NULL,

    return_date date NOT NULL,
    return_datetime timestamptz,

    product_id integer REFERENCES public.dim_product(product_id),
    product_sku_alias_id integer REFERENCES public.product_sku_alias(product_sku_alias_id),

    source_sku_code text,
    source_product_name text NOT NULL,

    quantity_returned numeric(18, 4) NOT NULL,
    unit text NOT NULL DEFAULT 'PCS',

    warehouse_id integer,
    source_warehouse_name text,

    source_from_raw text,
    source_box_raw text,

    source_file text NOT NULL,
    source_sheet text,
    source_row_number integer NOT NULL,
    raw_record_id text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_fact_internal_stock_return_not_production CHECK (
        source_return_type <> 'Produksi Harian'
    ),
    CONSTRAINT ck_fact_internal_stock_return_quantity_non_negative CHECK (
        quantity_returned >= 0
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_internal_stock_return_raw_record
ON public.fact_internal_stock_return (source_system, raw_record_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_internal_stock_return_source_row
ON public.fact_internal_stock_return (
    source_system,
    source_file,
    source_row_number
);

CREATE INDEX IF NOT EXISTS idx_fact_internal_stock_return_date
ON public.fact_internal_stock_return (return_date);

CREATE INDEX IF NOT EXISTS idx_fact_internal_stock_return_type
ON public.fact_internal_stock_return (source_return_type);

CREATE INDEX IF NOT EXISTS idx_fact_internal_stock_return_product
ON public.fact_internal_stock_return (product_id);

CREATE INDEX IF NOT EXISTS idx_fact_internal_stock_return_sku_alias
ON public.fact_internal_stock_return (product_sku_alias_id);

CREATE INDEX IF NOT EXISTS idx_fact_internal_stock_return_source_sku
ON public.fact_internal_stock_return (source_sku_code);

CREATE INDEX IF NOT EXISTS idx_fact_internal_stock_return_warehouse
ON public.fact_internal_stock_return (warehouse_id);

COMMIT;
