-- Raw material purchase facts.
-- Scope:
-- - Legacy raw material purchase header/detail exports from wellfarm_legacy.
-- - Latest Hasan "Bahan Baku" spreadsheet rows from the selected cutoff date.
--
-- Grain:
-- - fact_raw_material_purchase: one row per source PO receipt header.
-- - fact_raw_material_purchase_item: one row per source material line.
--
-- Safe to rerun.

BEGIN;

CREATE TABLE IF NOT EXISTS public.fact_raw_material_purchase (
    raw_material_purchase_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_system text NOT NULL,
    supplier_id integer REFERENCES public.dim_supplier(supplier_id),

    source_supplier_id text,
    source_supplier_name text NOT NULL,
    supplier_match_method text,

    po_number text NOT NULL,
    internal_po_number text,
    received_date date NOT NULL,

    total_quantity_kg numeric(18, 4),
    subtotal_amount numeric(18, 2),
    shipping_amount numeric(18, 2),
    source_total_amount numeric(18, 2),
    calculated_total_amount numeric(18, 2),
    total_amount numeric(18, 2),

    is_paid boolean,
    paid_amount numeric(18, 2),
    outstanding_amount numeric(18, 2),

    source_file text NOT NULL,
    source_sheet text,
    source_row_number integer NOT NULL,
    raw_record_id text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.fact_raw_material_purchase_item (
    raw_material_purchase_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_material_purchase_id bigint NOT NULL REFERENCES public.fact_raw_material_purchase(raw_material_purchase_id),

    source_system text NOT NULL,
    inventory_item_id integer REFERENCES public.dim_inventory_item(inventory_item_id),

    source_item_id text,
    source_item_code text,
    parsed_barcode text,
    source_item_name text NOT NULL,
    inventory_item_match_method text,

    quantity_kg numeric(18, 4) NOT NULL,
    unit_price numeric(18, 2),
    subtotal_amount numeric(18, 2),

    source_file text NOT NULL,
    source_sheet text,
    source_row_number integer NOT NULL,
    raw_record_id text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_fact_raw_material_purchase_item_quantity_positive CHECK (quantity_kg > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_raw_material_purchase_raw_record
ON public.fact_raw_material_purchase (source_system, raw_record_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_raw_material_purchase_item_raw_record
ON public.fact_raw_material_purchase_item (source_system, raw_record_id);

CREATE INDEX IF NOT EXISTS idx_fact_raw_material_purchase_received_date
ON public.fact_raw_material_purchase (received_date);

CREATE INDEX IF NOT EXISTS idx_fact_raw_material_purchase_supplier
ON public.fact_raw_material_purchase (supplier_id);

CREATE INDEX IF NOT EXISTS idx_fact_raw_material_purchase_po
ON public.fact_raw_material_purchase (po_number);

CREATE INDEX IF NOT EXISTS idx_fact_raw_material_purchase_source
ON public.fact_raw_material_purchase (source_system, source_file);

CREATE INDEX IF NOT EXISTS idx_fact_raw_material_purchase_item_header
ON public.fact_raw_material_purchase_item (raw_material_purchase_id);

CREATE INDEX IF NOT EXISTS idx_fact_raw_material_purchase_item_inventory
ON public.fact_raw_material_purchase_item (inventory_item_id);

CREATE INDEX IF NOT EXISTS idx_fact_raw_material_purchase_item_source_item
ON public.fact_raw_material_purchase_item (source_item_code, parsed_barcode);

COMMIT;
