-- Sales phase 5: marketplace balance / wallet movement facts.
-- Scope:
-- - Marketplace report files under sales_online/*/report
-- - Balance ledger rows such as earnings, withdrawals, seller balance spend,
--   ad top-up, payment, deposit, penalty, and non-order balance movements
--
-- Safe to rerun.

BEGIN;

CREATE TABLE IF NOT EXISTS public.fact_balance_transaction (
    balance_transaction_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_system text NOT NULL,
    sales_channel_type text NOT NULL DEFAULT 'online',

    marketplace_id integer REFERENCES public.dim_marketplace(marketplace_id),
    store_id integer REFERENCES public.dim_store(store_id),
    sales_order_id bigint REFERENCES public.fact_sales_order(sales_order_id),
    sales_settlement_id bigint REFERENCES public.fact_sales_settlement(sales_settlement_id),

    external_transaction_id text,
    external_order_id text,

    transaction_type text NOT NULL,
    transaction_sub_type text,
    transaction_status text,
    transaction_description text,
    transaction_description_key text,
    movement_direction text NOT NULL,

    raw_amount numeric(18, 2) NOT NULL,
    signed_amount numeric(18, 2) NOT NULL,
    amount_sign_from_source integer NOT NULL,
    balance_after_amount numeric(18, 2),
    currency_code text NOT NULL DEFAULT 'IDR',

    transaction_occurred_at timestamptz,
    transaction_requested_at timestamptz,
    transaction_succeeded_at timestamptz,
    bank_account text,

    source_table text,
    source_file text,
    source_sheet text,
    source_row_number integer,
    raw_record_id text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_fact_balance_transaction_direction CHECK (
        movement_direction IN ('credit', 'debit', 'zero')
    ),
    CONSTRAINT ck_fact_balance_transaction_amount_sign CHECK (
        amount_sign_from_source IN (-1, 0, 1)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_balance_transaction_raw_record
ON public.fact_balance_transaction (source_system, raw_record_id);

CREATE INDEX IF NOT EXISTS idx_fact_balance_transaction_store
ON public.fact_balance_transaction (marketplace_id, store_id);

CREATE INDEX IF NOT EXISTS idx_fact_balance_transaction_order
ON public.fact_balance_transaction (sales_order_id);

CREATE INDEX IF NOT EXISTS idx_fact_balance_transaction_settlement
ON public.fact_balance_transaction (sales_settlement_id);

CREATE INDEX IF NOT EXISTS idx_fact_balance_transaction_external_transaction
ON public.fact_balance_transaction (source_system, external_transaction_id);

CREATE INDEX IF NOT EXISTS idx_fact_balance_transaction_external_order
ON public.fact_balance_transaction (source_system, external_order_id);

CREATE INDEX IF NOT EXISTS idx_fact_balance_transaction_occurred_at
ON public.fact_balance_transaction (transaction_occurred_at);

CREATE INDEX IF NOT EXISTS idx_fact_balance_transaction_type
ON public.fact_balance_transaction (source_system, transaction_type, transaction_sub_type, transaction_status);

COMMIT;
