-- Production target fact.
-- Scope:
-- - Monthly production target from legacy fact_production_target.csv.
-- - Daily generated production target from legacy fact_production_daily_target.csv.
-- - Actual production output remains in fact_production_output.
--
-- Safe to rerun.

BEGIN;

CREATE TABLE IF NOT EXISTS public.fact_production_target (
    production_target_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_system text NOT NULL DEFAULT 'legacy_wellfarm',
    target_grain text NOT NULL,

    target_date date,
    target_year integer NOT NULL,
    target_month integer NOT NULL,
    target_day integer,
    target_cycle_start date,
    target_cycle_end date,

    product_id integer REFERENCES public.dim_product(product_id),
    product_sku_alias_id integer REFERENCES public.product_sku_alias(product_sku_alias_id),

    source_product_id text,
    source_sku_code text,
    source_product_name text,

    target_quantity numeric(18, 4) NOT NULL,
    weekly_need_quantity numeric(18, 4),
    unit text NOT NULL DEFAULT 'PCS',

    generated_at timestamptz,

    source_file text NOT NULL,
    source_sheet text,
    source_row_number integer NOT NULL,
    raw_record_id text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_fact_production_target_grain CHECK (
        target_grain IN ('monthly', 'daily')
    ),
    CONSTRAINT ck_fact_production_target_date_by_grain CHECK (
        (target_grain = 'monthly' AND target_date IS NULL)
        OR (target_grain = 'daily' AND target_date IS NOT NULL)
    ),
    CONSTRAINT ck_fact_production_target_quantity_non_negative CHECK (
        target_quantity >= 0
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_production_target_raw_record
ON public.fact_production_target (source_system, raw_record_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_production_target_source_row
ON public.fact_production_target (
    source_system,
    source_file,
    source_row_number
);

CREATE INDEX IF NOT EXISTS idx_fact_production_target_period
ON public.fact_production_target (target_year, target_month, target_day);

CREATE INDEX IF NOT EXISTS idx_fact_production_target_date
ON public.fact_production_target (target_date);

CREATE INDEX IF NOT EXISTS idx_fact_production_target_grain
ON public.fact_production_target (target_grain);

CREATE INDEX IF NOT EXISTS idx_fact_production_target_product
ON public.fact_production_target (product_id);

CREATE INDEX IF NOT EXISTS idx_fact_production_target_sku_alias
ON public.fact_production_target (product_sku_alias_id);

CREATE INDEX IF NOT EXISTS idx_fact_production_target_source_product
ON public.fact_production_target (source_product_id);

COMMIT;
