-- Data quality issue register.
-- Scope:
-- - Records unresolved links between sales money-flow phases
-- - Keeps source facts intact; this table only labels data-quality/treatment state
--
-- Safe to rerun.

BEGIN;

CREATE TABLE IF NOT EXISTS public.data_quality_issue (
    data_quality_issue_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    issue_key text NOT NULL,
    issue_domain text NOT NULL DEFAULT 'sales_money_flow',
    issue_type text NOT NULL,
    issue_severity text NOT NULL,
    issue_status text NOT NULL DEFAULT 'open',

    source_system text NOT NULL,
    sales_channel_type text,

    source_table text NOT NULL,
    source_pk_name text,
    source_pk_value text,

    marketplace_id integer,
    store_id integer,
    sales_order_id bigint,
    sales_settlement_id bigint,
    sales_settlement_adjustment_id bigint,
    balance_transaction_id bigint,
    sales_return_id bigint,
    sales_return_item_id bigint,
    sales_fulfillment_id bigint,

    external_order_id text,
    external_order_item_id text,
    external_transaction_id text,
    external_adjustment_id text,

    issue_amount numeric(18, 2),
    currency_code text NOT NULL DEFAULT 'IDR',
    issue_occurred_at timestamptz,

    issue_description text,
    recommended_treatment text,

    source_file text,
    source_sheet text,
    source_row_number integer,
    raw_record_id text,

    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    detected_by text NOT NULL DEFAULT 'scripts/audit/sales_data_quality_issues.py',
    run_id text,

    first_detected_at timestamptz NOT NULL DEFAULT now(),
    last_detected_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_data_quality_issue_key UNIQUE (issue_key),
    CONSTRAINT ck_data_quality_issue_domain CHECK (
        issue_domain IN ('sales_money_flow')
    ),
    CONSTRAINT ck_data_quality_issue_severity CHECK (
        issue_severity IN ('info', 'warning', 'critical')
    ),
    CONSTRAINT ck_data_quality_issue_status CHECK (
        issue_status IN ('open', 'accepted', 'resolved', 'ignored')
    )
);

ALTER TABLE public.data_quality_issue
ADD COLUMN IF NOT EXISTS issue_occurred_at timestamptz;

ALTER TABLE public.data_quality_issue
ADD COLUMN IF NOT EXISTS sales_return_id bigint;

ALTER TABLE public.data_quality_issue
ADD COLUMN IF NOT EXISTS sales_return_item_id bigint;

ALTER TABLE public.data_quality_issue
ADD COLUMN IF NOT EXISTS sales_fulfillment_id bigint;

CREATE INDEX IF NOT EXISTS idx_data_quality_issue_type_status
ON public.data_quality_issue (issue_type, issue_status);

CREATE INDEX IF NOT EXISTS idx_data_quality_issue_resolved_lookup
ON public.data_quality_issue (
    detected_by,
    issue_domain,
    issue_status,
    issue_type,
    source_system
);

CREATE INDEX IF NOT EXISTS idx_data_quality_issue_source
ON public.data_quality_issue (source_system, sales_channel_type);

CREATE INDEX IF NOT EXISTS idx_data_quality_issue_order
ON public.data_quality_issue (source_system, external_order_id);

CREATE INDEX IF NOT EXISTS idx_data_quality_issue_return
ON public.data_quality_issue (sales_return_id, sales_return_item_id);

CREATE INDEX IF NOT EXISTS idx_data_quality_issue_fulfillment
ON public.data_quality_issue (sales_fulfillment_id);

CREATE INDEX IF NOT EXISTS idx_data_quality_issue_store
ON public.data_quality_issue (marketplace_id, store_id);

CREATE INDEX IF NOT EXISTS idx_data_quality_issue_detected
ON public.data_quality_issue (last_detected_at);

CREATE INDEX IF NOT EXISTS idx_data_quality_issue_occurred
ON public.data_quality_issue (issue_occurred_at);

COMMIT;
