-- Sales return facts.
-- Scope:
-- - Return/refund/cancellation events from marketplace order files
-- - Kept separate from fact_sales_order/fact_sales_order_item so the original
--   sales grain remains intact.
--
-- Safe to rerun.

BEGIN;

CREATE TABLE IF NOT EXISTS public.fact_sales_return (
    sales_return_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_system text NOT NULL,
    sales_channel_type text NOT NULL DEFAULT 'online',

    marketplace_id integer,
    store_id integer,
    sales_order_id bigint REFERENCES public.fact_sales_order(sales_order_id),

    external_order_id text NOT NULL,
    external_return_id text NOT NULL,

    return_type text NOT NULL,
    return_status text,
    return_reason text,
    return_initiator text,

    return_requested_at timestamptz,
    return_completed_at timestamptz,

    currency_code text NOT NULL DEFAULT 'IDR',
    refund_amount numeric(18, 2),
    return_shipping_amount numeric(18, 2),

    source_file text,
    source_sheet text,
    source_row_number integer,
    raw_record_id text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_fact_sales_return_channel CHECK (
        sales_channel_type IN ('online', 'offline', 'b2b', 'manual')
    ),
    CONSTRAINT ck_fact_sales_return_type CHECK (
        return_type IN (
            'return_refund',
            'refund_only',
            'cancellation',
            'failed_delivery',
            'lost_or_damaged',
            'unknown'
        )
    )
);

CREATE TABLE IF NOT EXISTS public.fact_sales_return_item (
    sales_return_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_return_id bigint NOT NULL REFERENCES public.fact_sales_return(sales_return_id),

    source_system text NOT NULL,
    sales_order_item_id bigint REFERENCES public.fact_sales_order_item(sales_order_item_id),
    product_id integer,
    product_sku_alias_id integer,

    source_line_id text,
    source_sku_code text,
    source_product_name text,
    source_variation_name text,

    return_qty numeric(18, 4),
    unit text,
    refund_item_amount numeric(18, 2),
    item_status text,

    source_file text,
    source_sheet text,
    source_row_number integer,
    raw_record_id text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_sales_return_raw_record
ON public.fact_sales_return (source_system, raw_record_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_sales_return_item_raw_record
ON public.fact_sales_return_item (source_system, raw_record_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_return_order
ON public.fact_sales_return (sales_order_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_return_source_order
ON public.fact_sales_return (source_system, external_order_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_return_store
ON public.fact_sales_return (marketplace_id, store_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_return_requested_at
ON public.fact_sales_return (return_requested_at);

CREATE INDEX IF NOT EXISTS idx_fact_sales_return_completed_at
ON public.fact_sales_return (return_completed_at);

CREATE INDEX IF NOT EXISTS idx_fact_sales_return_item_return
ON public.fact_sales_return_item (sales_return_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_return_item_order_item
ON public.fact_sales_return_item (sales_order_item_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_return_item_product
ON public.fact_sales_return_item (product_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_return_item_sku_alias
ON public.fact_sales_return_item (product_sku_alias_id);

COMMIT;
