-- Sales fulfillment fact.
-- Scope:
-- - One row per sales order fulfillment/package/shipment lifecycle.
-- - Stores operational logistics timing from order/payment until delivery.
-- - Financial marketplace fee details remain in Phase 2-5 facts.
--
-- Safe to rerun.

BEGIN;

CREATE TABLE IF NOT EXISTS public.fact_sales_fulfillment (
    sales_fulfillment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_system text NOT NULL,
    sales_channel_type text NOT NULL DEFAULT 'online',

    marketplace_id integer,
    store_id integer,
    sales_order_id bigint REFERENCES public.fact_sales_order(sales_order_id),

    external_order_id text NOT NULL,
    external_order_group_id text,
    external_fulfillment_id text NOT NULL,
    external_package_id text,
    tracking_number text,
    tracking_url text,

    warehouse_id integer,
    source_warehouse_name text,

    shipping_service_id integer,
    source_shipping_provider text,
    source_shipping_service text,
    source_shipping_service_level text,

    fulfillment_status text,
    logistics_status text,
    handover_type text,
    is_dropship boolean,

    order_created_at timestamptz,
    paid_at timestamptz,
    ready_to_ship_at timestamptz,
    target_shipped_at timestamptz,
    pickup_at timestamptz,
    handover_at timestamptz,
    shipped_at timestamptz,
    delivered_at timestamptz,
    cancelled_at timestamptz,
    returned_at timestamptz,

    weight_kg numeric(18, 4),
    package_length_cm numeric(18, 4),
    package_width_cm numeric(18, 4),
    package_height_cm numeric(18, 4),
    distance_fee_amount numeric(18, 2),
    shipping_fee_amount numeric(18, 2),
    currency_code text NOT NULL DEFAULT 'IDR',

    destination_location_id integer,
    destination_city text,
    destination_province text,
    destination_postal_code text,
    destination_country text,

    source_file text,
    source_sheet text,
    source_row_number integer,
    raw_record_id text NOT NULL,

    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_fact_sales_fulfillment_channel CHECK (
        sales_channel_type IN ('online', 'offline', 'b2b', 'manual')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_sales_fulfillment_raw_record
ON public.fact_sales_fulfillment (source_system, raw_record_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fact_sales_fulfillment_source_grain
ON public.fact_sales_fulfillment (
    source_system,
    sales_channel_type,
    external_order_id,
    COALESCE(store_id, -1),
    external_fulfillment_id
);

CREATE INDEX IF NOT EXISTS idx_fact_sales_fulfillment_order
ON public.fact_sales_fulfillment (sales_order_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_fulfillment_source_order
ON public.fact_sales_fulfillment (source_system, external_order_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_fulfillment_store
ON public.fact_sales_fulfillment (marketplace_id, store_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_fulfillment_tracking
ON public.fact_sales_fulfillment (source_system, tracking_number);

CREATE INDEX IF NOT EXISTS idx_fact_sales_fulfillment_package
ON public.fact_sales_fulfillment (source_system, external_package_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_fulfillment_warehouse
ON public.fact_sales_fulfillment (warehouse_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_fulfillment_shipping_service
ON public.fact_sales_fulfillment (shipping_service_id);

CREATE INDEX IF NOT EXISTS idx_fact_sales_fulfillment_paid_at
ON public.fact_sales_fulfillment (paid_at);

CREATE INDEX IF NOT EXISTS idx_fact_sales_fulfillment_shipped_at
ON public.fact_sales_fulfillment (shipped_at);

CREATE INDEX IF NOT EXISTS idx_fact_sales_fulfillment_delivered_at
ON public.fact_sales_fulfillment (delivered_at);

COMMIT;
