-- Inventory item source alias table and initial packaging aliases.
-- Scope:
-- - Allows source-specific raw names/IDs to resolve to dim_inventory_item.
-- - Initial seed covers packaging purchase names from legacy fact_packaging_purchase.
-- - Numeric reject packaging_id aliases are intentionally not guessed here.
--
-- Safe to rerun.

BEGIN;

CREATE TABLE IF NOT EXISTS public.inventory_item_source_alias (
    inventory_item_source_alias_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    inventory_item_id integer NOT NULL REFERENCES public.dim_inventory_item(inventory_item_id),

    source_system text NOT NULL,
    source_entity text NOT NULL,
    source_alias_type text NOT NULL,
    source_alias text NOT NULL,
    source_alias_normalized text NOT NULL,

    match_confidence text NOT NULL DEFAULT 'high',
    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_inventory_item_source_alias_type CHECK (
        source_alias_type IN ('raw_name', 'source_id', 'item_code', 'legacy_product_id')
    ),
    CONSTRAINT ck_inventory_item_source_alias_confidence CHECK (
        match_confidence IN ('high', 'medium', 'low', 'needs_review')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_inventory_item_source_alias_source
ON public.inventory_item_source_alias (
    source_system,
    source_entity,
    source_alias_type,
    source_alias_normalized
);

CREATE INDEX IF NOT EXISTS idx_inventory_item_source_alias_item
ON public.inventory_item_source_alias (inventory_item_id);

CREATE INDEX IF NOT EXISTS idx_inventory_item_source_alias_lookup
ON public.inventory_item_source_alias (
    source_system,
    source_entity,
    source_alias_type,
    source_alias_normalized
)
WHERE is_active;

WITH missing_packaging_items (
    item_code,
    item_name,
    item_category,
    item_type,
    accurate_item_type,
    unit,
    is_active
) AS (
VALUES
    ('KARDUS-BEKAS-SGM', 'Kardus Bekas SGM', 'Kemasan Kardus', 'packaging', 'INV', 'PCS', true),
    ('KARDUS-CUSTOM-WELLFARM', 'Kardus Custom Wellfarm', 'Kemasan Kardus', 'packaging', 'INV', 'PCS', true),
    ('K-GENERIC-5KG', 'Kemasan Beras Generic 5 KG', 'Kemasan', 'packaging', 'INV', 'PCS', true)
)
INSERT INTO public.dim_inventory_item (
    item_code,
    item_name,
    item_category,
    item_type,
    accurate_item_type,
    unit,
    is_active
)
SELECT
    item_code,
    item_name,
    item_category,
    item_type,
    accurate_item_type,
    unit,
    is_active
FROM missing_packaging_items
ON CONFLICT (item_code) DO UPDATE SET
    item_name = EXCLUDED.item_name,
    item_category = EXCLUDED.item_category,
    item_type = EXCLUDED.item_type,
    accurate_item_type = EXCLUDED.accurate_item_type,
    unit = EXCLUDED.unit,
    is_active = EXCLUDED.is_active,
    updated_at = now();

WITH seed (
    source_alias,
    item_code,
    match_confidence,
    notes
) AS (
VALUES
    ('Beras Amazinc 1 Kg', 'K-8997224980909', 'high', 'Legacy packaging purchase raw name.'),
    ('Beras Diabet 1 Kg', 'K-8997224980831', 'high', 'Legacy packaging purchase raw name.'),
    ('Beras Diabet 5 Kg', 'K - 8997224981142', 'high', 'Legacy packaging purchase raw name.'),
    ('Beras Diet 1 Kg', 'K-8997224980824', 'high', 'Legacy packaging purchase raw name.'),
    ('Beras Hitam 1 Kg', 'K-8997224980879', 'high', 'Legacy packaging purchase raw name.'),
    ('Beras Menthik Susu 1 Kg', 'K-8997224980886', 'high', 'Legacy packaging purchase raw name.'),
    ('Beras Menthik Wangi 1 Kg', 'K-8997224980893', 'high', 'Legacy packaging purchase raw name.'),
    ('Beras Merah 1 Kg', 'K-8997224980855', 'high', 'Legacy packaging purchase raw name.'),
    ('Beras Obirice 1 Kg', 'K-8997224980848', 'high', 'Legacy packaging purchase raw name.'),
    ('Beras Porang 1 Kg', 'K-8997224981104', 'high', 'Legacy packaging purchase raw name.'),
    ('Beras Porang 240 gr', 'K-8997224981111', 'high', 'Legacy packaging purchase raw name.'),
    ('Beras Porang 40 gr', 'K-8997224981135', 'high', 'Legacy packaging purchase raw name.'),
    ('Kardus Bekas SGM', 'KARDUS-BEKAS-SGM', 'high', 'Legacy packaging purchase raw name; added as packaging inventory item.'),
    ('Kardus Custom Wellfarm', 'KARDUS-CUSTOM-WELLFARM', 'high', 'Legacy packaging purchase raw name; added as packaging inventory item.'),
    ('Kemasan 5 Kg', 'K-GENERIC-5KG', 'medium', 'Legacy packaging purchase raw name; generic 5 KG packaging, not product-specific.')
),
resolved AS (
    SELECT
        di.inventory_item_id,
        seed.source_alias,
        LOWER(TRIM(REGEXP_REPLACE(seed.source_alias, '[^a-zA-Z0-9]+', ' ', 'g'))) AS source_alias_normalized,
        seed.match_confidence,
        seed.notes
    FROM seed
    JOIN public.dim_inventory_item di
      ON di.item_code = seed.item_code
)
INSERT INTO public.inventory_item_source_alias (
    inventory_item_id,
    source_system,
    source_entity,
    source_alias_type,
    source_alias,
    source_alias_normalized,
    match_confidence,
    is_active,
    notes
)
SELECT
    inventory_item_id,
    'legacy_wellfarm' AS source_system,
    'fact_packaging_purchase' AS source_entity,
    'raw_name' AS source_alias_type,
    source_alias,
    source_alias_normalized,
    match_confidence,
    true AS is_active,
    notes
FROM resolved
ON CONFLICT (
    source_system,
    source_entity,
    source_alias_type,
    source_alias_normalized
) DO UPDATE SET
    inventory_item_id = EXCLUDED.inventory_item_id,
    source_alias = EXCLUDED.source_alias,
    match_confidence = EXCLUDED.match_confidence,
    is_active = EXCLUDED.is_active,
    notes = EXCLUDED.notes,
    updated_at = now();

-- Review helper for reject source IDs. These are not mapped here because the
-- legacy packaging master table was not part of the available export.
SELECT
    'inventory_item_source_alias' AS table_name,
    COUNT(*) AS active_packaging_purchase_aliases
FROM public.inventory_item_source_alias
WHERE source_system = 'legacy_wellfarm'
  AND source_entity = 'fact_packaging_purchase'
  AND source_alias_type = 'raw_name'
  AND is_active;

COMMIT;
