"""Column mapping constants copied from src.extract_loader."""

LAZADA_ORDER_COLUMN_MAP = {
    'orderItemId'                        : 'order_item_id',
    'orderType'                          : 'order_type',
    'Guarantee'                          : 'guarantee',
    'deliveryType'                       : 'delivery_type',
    'lazadaId'                           : 'lazada_id',
    'sellerSku'                          : 'seller_sku',
    'lazadaSku'                          : 'lazada_sku',
    'wareHouse'                          : 'warehouse',
    'createTime'                         : 'create_time',
    'updateTime'                         : 'update_time',
    'rtsSla'                             : 'rts_sla',
    'ttsSla'                             : 'tts_sla',
    'orderNumber'                        : 'order_number',
    'invoiceRequired'                    : 'invoice_required',
    'invoiceNumber'                      : 'invoice_number',
    'deliveredDate'                      : 'delivered_date',
    'customerName'                       : 'customer_name',
    'customerEmail'                      : 'customer_email',
    'nationalRegistrationNumber'         : 'national_registration_number',
    'shippingName'                       : 'shipping_name',
    'shippingAddress'                    : 'shipping_address',
    'shippingAddress2'                   : 'shipping_address2',
    'shippingAddress3'                   : 'shipping_address3',
    'shippingAddress4'                   : 'shipping_address4',
    'shippingAddress5'                   : 'shipping_address5',
    'shippingPhone'                      : 'shipping_phone',
    'shippingPhone2'                     : 'shipping_phone2',
    'shippingCity'                       : 'shipping_city',
    'shippingPostCode'                   : 'shipping_post_code',
    'shippingCountry'                    : 'shipping_country',
    'shippingRegion'                     : 'shipping_region',
    'billingName'                        : 'billing_name',
    'billingAddr'                        : 'billing_addr',
    'billingAddr2'                       : 'billing_addr2',
    'billingAddr3'                       : 'billing_addr3',
    'billingAddr4'                       : 'billing_addr4',
    'billingAddr5'                       : 'billing_addr5',
    'billingPhone'                       : 'billing_phone',
    'billingPhone2'                      : 'billing_phone2',
    'billingCity'                        : 'billing_city',
    'billingPostCode'                    : 'billing_post_code',
    'billingCountry'                     : 'billing_country',
    'taxCode'                            : 'tax_code',
    'branchNumber'                       : 'branch_number',
    'taxInvoiceRequested'                : 'tax_invoice_requested',
    'payMethod'                          : 'pay_method',
    'paidPrice'                          : 'paid_price',
    'unitPrice'                          : 'unit_price',
    'sellerDiscountTotal'                : 'seller_discount_total',
    'platformDiscountTotal'              : 'platform_discount_total',
    'shippingFee'                        : 'shipping_fee',
    'walletCredit'                       : 'wallet_credit',
    'itemName'                           : 'item_name',
    'variation'                          : 'variation',
    'cdShippingProvider'                 : 'cd_shipping_provider',
    'shippingProvider'                   : 'shipping_provider',
    'shipmentTypeName'                   : 'shipment_type_name',
    'shippingProviderType'               : 'shipping_provider_type',
    'cdTrackingCode'                     : 'cd_tracking_code',
    'trackingCode'                       : 'tracking_code',
    'trackingUrl'                        : 'tracking_url',
    'shippingProviderFM'                 : 'shipping_provider_fm',
    'trackingCodeFM'                     : 'tracking_code_fm',
    'trackingUrlFM'                      : 'tracking_url_fm',
    'promisedShippingTime'               : 'promised_shipping_time',
    'premium'                            : 'premium',
    'status'                             : 'status',
    'buyerFailedDeliveryReturnInitiator' : 'buyer_failed_delivery_return_initiator',
    'buyerFailedDeliveryReason'          : 'buyer_failed_delivery_reason',
    'buyerFailedDeliveryDetail'          : 'buyer_failed_delivery_detail',
    'buyerFailedDeliveryUserName'        : 'buyer_failed_delivery_user_name',
    'bundleId'                           : 'bundle_id',
    'semiManaged'                        : 'semi_managed',
    'flexibleDeliveryTime'               : 'flexible_delivery_time',
    'bundleDiscount'                     : 'bundle_discount',
    'refundAmount'                       : 'refund_amount',
    'sellerNote'                         : 'seller_note',
}

LAZADA_INCOME_COLUMN_MAP = {
    'Periode Laporan'                    : 'periode_laporan',
    'Nomor Laporan'                      : 'nomor_laporan',
    'Tanggal Transaksi'                  : 'tanggal_transaksi',
    'Nama Biaya'                         : 'nama_biaya',
    'Jumlah (Termasuk Pajak)'            : 'jumlah_termasuk_pajak',
    'VAT Amount'                         : 'vat_amount',
    'Status Pelepasan Dana'              : 'status_pelepasan_dana',
    'Tanggal Dilepas'                    : 'tanggal_dilepas',
    'Komentar'                           : 'komentar',
    'Tanggal Pesanan Dibuat'             : 'tanggal_pesanan_dibuat',
    'Nomor Pesanan'                      : 'nomor_pesanan',
    'ID Pesanan'                         : 'id_pesanan',
    'SKU Penjual'                        : 'sku_penjual',
    'Lazada SKU'                         : 'lazada_sku',
    'WHT Amount'                         : 'wht_amount',
    'WHT termasuk dalam jumlah'          : 'wht_termasuk_dalam_jumlah',
    'Status Pesanan'                     : 'status_pesanan',
    'Nama Produk'                        : 'nama_produk',
    'Short Code'                         : 'short_code',
}

LAZADA_REPORT_COLUMN_MAP = {
    'Transaction Number'                 : 'transaction_number',
    'Transaction Time'                   : 'transaction_time',
    'Type'                               : 'type',
    'Sub Type'                           : 'sub_type',
    'Amount'                             : 'amount',
    'Remarks'                            : 'remarks',
}
