"""Column mapping constants copied from src.extract_loader."""

SHOPEE_ORDER_COLUMN_MAP = {
    'No. Pesanan'                                                         : 'no_pesanan',
    'Status Pesanan'                                                      : 'status_pesanan',
    'Alasan Pembatalan'                                                   : 'alasan_pembatalan',
    'Status Pembatalan/ Pengembalian'                                     : 'status_pembatalan_pengembalian',
    'No. Resi'                                                            : 'no_resi',
    'Opsi Pengiriman'                                                     : 'opsi_pengiriman',
    'Antar ke counter/ pick-up'                                           : 'antar_ke_counter_pickup',
    'Pesanan Harus Dikirimkan Sebelum (Menghindari keterlambatan)'        : 'pesanan_harus_dikirimkan_sebelum',
    'Waktu Pengiriman Diatur'                                             : 'waktu_pengiriman_diatur',
    'Waktu Pesanan Dibuat'                                                : 'waktu_pesanan_dibuat',
    'Waktu Pembayaran Dilakukan'                                          : 'waktu_pembayaran_dilakukan',
    'Metode Pembayaran'                                                   : 'metode_pembayaran',
    'SKU Induk'                                                           : 'sku_induk',
    'Nama Produk'                                                         : 'nama_produk',
    'Nomor Referensi SKU'                                                 : 'nomor_referensi_sku',
    'Nama Variasi'                                                        : 'nama_variasi',
    'Harga Awal'                                                          : 'harga_awal',
    'Harga Setelah Diskon'                                                : 'harga_setelah_diskon',
    'Jumlah'                                                              : 'jumlah',
    'Returned quantity'                                                   : 'returned_quantity',
    'Dibayar Pembeli'                                                     : 'total_harga_produk',
    'Total Harga Produk'                                                  : 'total_harga_produk',
    'Total Diskon'                                                        : 'total_diskon',
    'Diskon Dari Penjual'                                                 : 'diskon_dari_penjual',
    'Diskon Dari Shopee'                                                  : 'diskon_dari_shopee',
    'Berat Produk'                                                        : 'berat_produk',
    'Jumlah Produk di Pesan'                                              : 'jumlah_produk_di_pesan',
    'Total Berat'                                                         : 'total_berat',
    'Nama Gudang'                                                         : 'nama_gudang',
    'Voucher Ditanggung Penjual'                                          : 'voucher_ditanggung_penjual',
    'Cashback Koin'                                                       : 'cashback_koin',
    'Voucher Ditanggung Shopee'                                           : 'voucher_ditanggung_shopee',
    'Paket Diskon'                                                        : 'paket_diskon',
    'Paket Diskon (Diskon dari Shopee)'                                   : 'paket_diskon_dari_shopee',
    'Paket Diskon (Diskon dari Penjual)'                                  : 'paket_diskon_dari_penjual',
    'Potongan Koin Shopee'                                                : 'potongan_koin_shopee',
    'Diskon Kartu Kredit'                                                 : 'diskon_kartu_kredit',
    'Ongkos Kirim Dibayar oleh Pembeli'                                   : 'ongkos_kirim_dibayar_oleh_pembeli',
    'Estimasi Potongan Biaya Pengiriman'                                  : 'estimasi_potongan_biaya_pengiriman',
    'Ongkos Kirim Pengembalian Barang'                                    : 'ongkos_kirim_pengembalian_barang',
    'Total Pembayaran'                                                    : 'total_pembayaran',
    'Perkiraan Ongkos Kirim'                                              : 'perkiraan_ongkos_kirim',
    'Catatan dari Pembeli'                                                : 'catatan_dari_pembeli',
    'Catatan'                                                             : 'catatan',
    'Username (Pembeli)'                                                  : 'username_pembeli',
    'Nama Penerima'                                                       : 'nama_penerima',
    'No. Telepon'                                                         : 'no_telepon',
    'Alamat Pengiriman'                                                   : 'alamat_pengiriman',
    'Kota/Kabupaten'                                                      : 'kota_kabupaten',
    'Provinsi'                                                            : 'provinsi',
    'Waktu Pesanan Selesai'                                               : 'waktu_pesanan_selesai',
}

SHOPEE_INCOME_MAIN_COLUMN_MAP = {
    'No.'                                                                 : 'no',
    'No. Pesanan'                                                         : 'no_pesanan',
    'No. Pengajuan'                                                       : 'no_pengajuan',
    'Username (Pembeli)'                                                  : 'username_pembeli',
    'Waktu Pesanan Dibuat'                                                : 'waktu_pesanan_dibuat',
    'Metode pembayaran pembeli'                                           : 'metode_pembayaran_pembeli',
    'Tanggal Dana Dilepaskan'                                             : 'tanggal_dana_dilepaskan',
    'Harga Asli Produk'                                                   : 'harga_asli_produk',
    'Total Diskon Produk'                                                 : 'total_diskon_produk',
    'Jumlah Pengembalian Dana ke Pembeli'                                 : 'jumlah_pengembalian_dana_ke_pembeli',
    'Diskon Produk dari Shopee'                                           : 'diskon_produk_dari_shopee',
    'Voucher disponsor oleh Penjual'                                      : 'voucher_disponsor_oleh_penjual',
    'Voucher co-fund disponsor oleh Penjual'                              : 'voucher_co_fund_disponsor_oleh_penjual',
    'Cashback Koin disponsori Penjual'                                    : 'cashback_koin_disponsori_penjual',
    'Cashback Koin Co-fund disponsori Penjual'                            : 'cashback_koin_co_fund_disponsori_penjual',
    'Ongkir Dibayar Pembeli'                                              : 'ongkir_dibayar_pembeli',
    'Diskon Ongkir Ditanggung Jasa Kirim'                                 : 'diskon_ongkir_ditanggung_jasa_kirim',
    'Gratis Ongkir dari Shopee'                                           : 'gratis_ongkir_dari_shopee',
    'Ongkir yang Diteruskan oleh Shopee ke Jasa Kirim'                    : 'ongkir_yang_diteruskan_oleh_shopee_ke_jasa_kirim',
    'Ongkos Kirim Pengembalian Barang'                                    : 'ongkos_kirim_pengembalian_barang',
    'Kembali ke Biaya Pengiriman Pengirim'                                : 'kembali_ke_biaya_pengiriman_pengirim',
    'Pengembalian Biaya Kirim'                                            : 'pengembalian_biaya_kirim',
    'Biaya Komisi AMS'                                                    : 'biaya_komisi_ams',
    'Biaya Administrasi (termasuk PPN 11%)'                               : 'biaya_administrasi_termasuk_ppn_11',
    'Biaya Administrasi'                                                  : 'biaya_administrasi_termasuk_ppn_11',
    'Biaya Layanan'                                                       : 'biaya_layanan',
    'Biaya Proses Pesanan'                                                : 'biaya_proses_pesanan',
    'Premi'                                                               : 'premi',
    'Biaya Program Hemat Biaya Kirim'                                     : 'biaya_program_hemat_biaya_kirim',
    'Biaya Transaksi'                                                     : 'biaya_transaksi',
    'Biaya Kampanye'                                                      : 'biaya_kampanye',
    'Bea Masuk, PPN & PPh'                                                : 'bea_masuk_ppn_pph',
    'Biaya Isi Saldo Otomatis (dari Penghasilan)'                         : 'biaya_isi_saldo_otomatis_dari_penghasilan',
    'Total Penghasilan'                                                   : 'total_penghasilan',
    'Kode Voucher'                                                        : 'kode_voucher',
    'Kompensasi'                                                          : 'kompensasi',
    'Promo Gratis Ongkir dari Penjual'                                    : 'promo_gratis_ongkir_dari_penjual',
    'Jasa Kirim'                                                          : 'jasa_kirim',
    'Nama Kurir'                                                          : 'nama_kurir',
    'Pengembalian Dana ke Pembeli'                                        : 'pengembalian_dana_ke_pembeli',
    'Pro-rata Koin yang Ditukarkan untuk Pengembalian Barang'             : 'pro_rata_koin_yang_ditukarkan_untuk_pengembalian_barang',
    'Pro-rata Voucher Shopee untuk Pengembalian Barang'                   : 'pro_rata_voucher_shopee_untuk_pengembalian_barang',
    'Pro-rated Bank Payment Channel Promotion for return refund Items'    : 'pro_rated_bank_payment_channel_promotion_for_return_refund_item',
    'Pro-rated Bank Payment Channel Promotion  for return refund Items'   : 'pro_rated_bank_payment_channel_promotion_for_return_refund_item',
    'Pro-rated Shopee Payment Channel Promotion for return refund Items'  : 'pro_rated_shopee_payment_channel_promotion_for_return_refund_it',
    'Pro-rated Shopee Payment Channel Promotion  for return refund Items' : 'pro_rated_shopee_payment_channel_promotion_for_return_refund_it',
}

SHOPEE_INCOME_OPF_COLUMN_MAP = {
    'No.'                                                                 : 'no',
    'Lihat berdasarkan'                                                   : 'lihat_berdasarkan',
    'No. Pesanan'                                                         : 'no_pesanan',
    'ID Produk'                                                           : 'id_produk',
    'Nama Produk'                                                         : 'nama_produk',
    'Biaya Proses Pesanan'                                                : 'biaya_proses_pesanan',
    'Biaya Proses Pesanan per Produk (Prorata harga produk tiap pesanan)' : 'biaya_proses_pesanan_per_produk_prorata',
}

SHOPEE_INCOME_SF_COLUMN_MAP = {
    'No.'                                   : 'no',
    'No. Pesanan'                           : 'no_pesanan',
    'Biaya Layanan Cashback XTRA'           : 'biaya_layanan_cashback_xtra',
    'Biaya Layanan Cashback Xtra'           : 'biaya_layanan_cashback_xtra',
    'Biaya Layanan CashbackXTRA'            : 'biaya_layanan_cashbackxtra',
    'Biaya Layanan Gratis Ongkir XTRA'      : 'biaya_layanan_gratis_ongkir_xtra',
    'Biaya Layanan Gratis Ongkir Xtra'      : 'biaya_layanan_gratis_ongkir_xtra_2',
    'Biaya Layanan Promo XTRA'              : 'biaya_layanan_promo_xtra',
    'Biaya Pembayaran'                      : 'biaya_pembayaran',
    'Biaya Program Shopee Live Xtra'        : 'biaya_program_shopee_live_xtra',
    'Biaya Campaign 1.1 2024'               : 'biaya_campaign_1_1',
    'Biaya Campaign 2.2 2024'               : 'biaya_campaign_2_2',
    'Biaya Campaign 3.3 2024'               : 'biaya_campaign_3_3',
    'Biaya Campaign 4.4 2024'               : 'biaya_campaign_4_4',
    'Biaya Campaign 5.5 2024'               : 'biaya_campaign_5_5',
    'Biaya Campaign 6.6 2024'               : 'biaya_campaign_6_6',
    'Biaya Campaign 7.7 2024'               : 'biaya_campaign_7_7',
    'Biaya Campaign 8.8 2024'               : 'biaya_campaign_8_8',
    'Biaya Campaign 9.9 2024'               : 'biaya_campaign_9_9',
    'Biaya Campaign 10.10 2024'             : 'biaya_campaign_10_10',
    'Biaya Campaign 11.11 2024'             : 'biaya_campaign_11_11',
    'Biaya Campaign 12.12 2024'             : 'biaya_campaign_12_12',
    'Biaya Campaign 1.1 2025'               : 'biaya_campaign_1_1',
    'Biaya Campaign 2.2 2025'               : 'biaya_campaign_2_2',
    'Biaya Campaign 3.3 2025'               : 'biaya_campaign_3_3',
    'Biaya Campaign 4.4 2025'               : 'biaya_campaign_4_4',
    'Biaya Campaign 5.5 2025'               : 'biaya_campaign_5_5',
    'Biaya Campaign 6.6 2025'               : 'biaya_campaign_6_6',
    'Biaya Campaign 7.7 2025'               : 'biaya_campaign_7_7',
    'Biaya Campaign 8.8 2025'               : 'biaya_campaign_8_8',
    'Biaya Campaign 9.9 2025'               : 'biaya_campaign_9_9',
    'Biaya Campaign 10.10 2025'             : 'biaya_campaign_10_10',
    'Biaya Campaign 11.11 2025'             : 'biaya_campaign_11_11',
    'Biaya Campaign 12.12 2025'             : 'biaya_campaign_12_12',
    'Biaya Proses Pesanan'                  : 'biaya_proses_pesanan',
}

SHOPEE_INCOME_SD_COLUMN_MAP = {
    'No. Pesanan'                                   : 'no_pesanan',
    'Estimasi Ongkos Kirim:'                        : 'estimasi_ongkos_kirim',
    'Ongkos Kirim yang Dibayarkan ke Jasa Kirim:'   : 'ongkos_kirim_yang_dibayarkan_ke_jasa_kirim',
    'Discrepancy reason'                            : 'discrepancy_reason',
}

SHOPEE_INCOME_ADJ_COLUMN_MAP = {
    'No.'                                           : 'no',
    'Tanggal Penyesuaian Dibuat'                    : 'tanggal_penyesuaian_dibuat',
    'Tipe Penyesuaian | Deskripsi'                  : 'tipe_penyesuaian_deskripsi',
    'Alasan Penyesuaian'                            : 'alasan_penyesuaian',
    'Biaya Penyesuaian'                             : 'biaya_penyesuaian',
    'No. Pesanan Terhubung'                         : 'no_pesanan_terhubung',
    'Tanggal Dana Dilepaskan'                       : 'tanggal_dana_dilepaskan',
}

SHOPEE_REPORT_COLUMN_MAP = {
    'Tanggal Transaksi'                             : 'tanggal_transaksi',
    'Tipe Transaksi'                                : 'tipe_transaksi',
    'Deskripsi'                                     : 'deskripsi',
    'No. Pesanan'                                   : 'no_pesanan',
    'Jenis Transaksi'                               : 'jenis_transaksi',
    'Jumlah'                                        : 'jumlah',
    'Status'                                        : 'status',
    'Saldo Akhir'                                   : 'saldo_akhir',
}
