"""Column mapping constants copied from src.extract_loader."""

TIKTOK_ORDER_COLUMN_MAP = {
    'Order ID'                            : 'order_id',
    'Order Status'                        : 'order_status',
    'Order Substatus'                     : 'order_substatus',
    'Cancelation/Return Type'             : 'cancelation_return_type',
    'Normal or Pre-order'                 : 'normal_or_pre_order',
    'SKU ID'                              : 'sku_id',
    'Seller SKU'                          : 'seller_sku',
    'Product Name'                        : 'product_name',
    'Variation'                           : 'variation',
    'Quantity'                            : 'quantity',
    'Sku Quantity of return'              : 'sku_quantity_of_return',
    'SKU Unit Original Price'             : 'sku_unit_original_price',
    'SKU Subtotal Before Discount'        : 'sku_subtotal_before_discount',
    'SKU Platform Discount'               : 'sku_platform_discount',
    'SKU Seller Discount'                 : 'sku_seller_discount',
    'SKU Subtotal After Discount'         : 'sku_subtotal_after_discount',
    'Shipping Fee After Discount'         : 'shipping_fee_after_discount',
    'Original Shipping Fee'               : 'original_shipping_fee',
    'Shipping Fee Seller Discount'        : 'shipping_fee_seller_discount',
    'Shipping Fee Platform Discount'      : 'shipping_fee_platform_discount',
    'Distance Shipping Fee'               : 'distance_shipping_fee',
    'Distance Fee'                        : 'distance_fee',
    'Order Refund Amount'                 : 'order_refund_amount',
    'Payment platform discount'           : 'payment_platform_discount',
    'Buyer Service Fee'                   : 'buyer_service_fee',
    'Handling Fee'                        : 'handling_fee',
    'Shipping Insurance'                  : 'shipping_insurance',
    'Item Insurance'                      : 'item_insurance',
    'Order Amount'                        : 'order_amount',
    'Created Time'                        : 'created_time',
    'Paid Time'                           : 'paid_time',
    'RTS Time'                            : 'rts_time',
    'Shipped Time'                        : 'shipped_time',
    'Delivered Time'                      : 'delivered_time',
    'Cancelled Time'                      : 'cancelled_time',
    'Cancel By'                           : 'cancel_by',
    'Cancel Reason'                       : 'cancel_reason',
    'Fulfillment Type'                    : 'fulfillment_type',
    'Warehouse Name'                      : 'warehouse_name',
    'Tracking ID'                         : 'tracking_id',
    'Delivery Option'                     : 'delivery_option',
    'Shipping Provider Name'              : 'shipping_provider_name',
    'Buyer Message'                       : 'buyer_message',
    'Buyer Username'                      : 'buyer_username',
    'Recipient'                           : 'recipient',
    'Phone #'                             : 'phone_number',
    'Zipcode'                             : 'zipcode',
    'Country'                             : 'country',
    'Province'                            : 'province',
    'Regency and City'                    : 'regency_and_city',
    'Districts'                           : 'districts',
    'Villages'                            : 'villages',
    'Detail Address'                      : 'detail_address',
    'Additional address information'      : 'additional_address_information',
    'Payment Method'                      : 'payment_method',
    'Weight(kg)'                          : 'weight_kg',
    'Product Category'                    : 'product_category',
    'Package ID'                          : 'package_id',
    'Purchase Channel'                    : 'purchase_channel',
    'Seller Note'                         : 'seller_note',
    'Checked Status'                      : 'checked_status',
    'Checked Marked by'                   : 'checked_marked_by',
    'Tokopedia Invoice Number'            : 'tokopedia_invoice_number',
}

TIKTOK_INCOME_COLUMN_MAP = {
    'Order/adjustment ID'                                  : 'order_adjustment_id',
    'ID Pesanan/Penyesuaian'                               : 'order_adjustment_id',
    'Type'                                                 : 'type',
    'Jenis transaksi'                                      : 'type',
    'Order created time'                                   : 'order_created_time',
    'Waktu pemesanan'                                      : 'order_created_time',
    'Order settled time'                                   : 'order_settled_time',
    'Waktu pembayaran pesanan'                             : 'order_settled_time',
    'Currency'                                             : 'currency',
    'Mata uang'                                            : 'currency',
    'Total settlement amount'                              : 'total_settlement_amount',
    'Jumlah penyelesaian pembayaran'                       : 'total_settlement_amount',
    'Total Revenue'                                        : 'total_revenue',
    'Total Pendapatan'                                     : 'total_revenue',
    'Subtotal after seller discounts'                      : 'subtotal_after_seller_discounts',
    'Subtotal setelah diskon penjual'                      : 'subtotal_after_seller_discounts',
    'Subtotal before discounts'                            : 'subtotal_before_discounts',
    'Subtotal sebelum diskon'                              : 'subtotal_before_discounts',
    'Seller discounts'                                     : 'seller_discounts',
    'Diskon penjual'                                       : 'seller_discounts',
    'Distance item fee from Horizon+ Program'              : 'distance_item_fee_from_horizon_plus_program',
    'Biaya produk sesuai jarak dari Program Horison+'      : 'distance_item_fee_from_horizon_plus_program',
    'Refund subtotal after seller discounts'               : 'refund_subtotal_after_seller_discounts',
    'Subtotal pengembalian dana setelah diskon penjual'    : 'refund_subtotal_after_seller_discounts',
    'Refund subtotal before seller discounts'              : 'refund_subtotal_before_seller_discounts',
    'Subtotal pengembalian dana sebelum diskon penjual'    : 'refund_subtotal_before_seller_discounts',
    'Refund of seller discounts'                           : 'refund_of_seller_discounts',
    'Pengembalian dana diskon penjual'                     : 'refund_of_seller_discounts',
    'Total Fees'                                           : 'total_fees',
    'Total Biaya'                                          : 'total_fees',
    'Platform commission fee'                              : 'platform_commission_fee',
    'Biaya komisi platform'                                : 'platform_commission_fee',
    'Pre-order service fee'                                : 'pre_order_service_fee',
    'Biaya layanan pre-order'                              : 'pre_order_service_fee',
    'Mall service fee'                                     : 'mall_service_fee',
    'Biaya layanan Mall'                                   : 'mall_service_fee',
    'Payment Fee'                                          : 'payment_fee',
    'Biaya Pembayaran'                                     : 'payment_fee',
    'Biaya komisi sebelum diskon'                          : 'platform_commission_before_discount',
    'Diskon (dari belanja iklan)'                          : 'ads_discount',
    'Diskon komisi lainnya'                                : 'other_commission_discount',
    'Credit card installment - Handling fee'                : 'credit_card_installment_handling_fee',
    'Shipping cost'                                        : 'shipping_cost',
    'Ongkir'                                               : 'shipping_cost',
    'Shipping costs passed on to the logistics provider'   : 'shipping_costs_passed_on_to_the_logistics_provider',
    'Ongkir yang ditalangi penyedia jasa logistik'         : 'shipping_costs_passed_on_to_the_logistics_provider',
    'Replacement shipping fee (passed on to the customer)' : 'replacement_shipping_fee_passed_on_to_the_customer',
    'Ongkir penggantian (ditanggung pembeli)'              : 'replacement_shipping_fee_passed_on_to_the_customer',
    'Exchange shipping fee (passed on to the customer)'    : 'exchange_shipping_fee_passed_on_to_the_customer',
    'Ongkir penukaran (ditanggung pembeli)'                : 'exchange_shipping_fee_passed_on_to_the_customer',
    'Shipping cost borne by the platform'                  : 'shipping_cost_borne_by_the_platform',
    'Ongkir yang ditanggung platform'                      : 'shipping_cost_borne_by_the_platform',
    'Shipping cost paid by the customer'                   : 'shipping_cost_paid_by_the_customer',
    'Ongkir yang ditanggung pembeli'                       : 'shipping_cost_paid_by_the_customer',
    'Refunded shipping cost paid by the customer'          : 'refunded_shipping_cost_paid_by_the_customer',
    'Pengembalian ongkir yang ditanggung pembeli'          : 'refunded_shipping_cost_paid_by_the_customer',
    'Return shipping costs (passed on to the customer)'    : 'return_shipping_costs_passed_on_to_the_customer',
    'Ongkir pengembalian barang (yang ditanggung pembeli)' : 'return_shipping_costs_passed_on_to_the_customer',
    'Shipping cost subsidy'                                : 'shipping_cost_subsidy',
    'Subsidi ongkir'                                       : 'shipping_cost_subsidy',
    'Distance shipping fee from Horizon+ Program'          : 'distance_shipping_fee_from_horizon_plus_program',
    'Biaya pengiriman sesuai jarak dari Program Horison+'  : 'distance_shipping_fee_from_horizon_plus_program',
    'Affiliate Commission'                                 : 'affiliate_commission',
    'Komisi Afiliasi'                                      : 'affiliate_commission',
    'Affiliate partner commission'                         : 'affiliate_partner_commission',
    'Komisi mitra afiliasi'                                : 'affiliate_partner_commission',
    'Affiliate Shop Ads commission'                        : 'affiliate_shop_ads_commission',
    'Komisi Iklan Toko afiliasi'                           : 'affiliate_shop_ads_commission',
    'Deposit komisi afiliasi'                              : 'affiliate_commission_deposit',
    'Pengembalian dana komisi afiliasi'                    : 'affiliate_commission_refund',
    'Affiliate Partner shop ads commission'                : 'affiliate_partner_shop_ads_commission',
    'Komisi iklan toko Mitra Afiliasi'                     : 'affiliate_partner_shop_ads_commission',
    'Shipping Fee Program service fee'                     : 'shipping_fee_program_service_fee',
    'Biaya layanan Program Bebas Ongkir'                   : 'shipping_fee_program_service_fee',
    'Dynamic commission'                                   : 'dynamic_commission',
    'Komisi dinamis'                                       : 'dynamic_commission',
    'Bonus cashback service fee'                           : 'bonus_cashback_service_fee',
    'Biaya layanan cashback bonus'                         : 'bonus_cashback_service_fee',
    'LIVE Specials service fee'                            : 'live_specials_service_fee',
    'Biaya layanan Khusus LIVE'                            : 'live_specials_service_fee',
    'Voucher Xtra service fee'                             : 'voucher_xtra_service_fee',
    'Biaya akses keuntungan eksklusif'                     : 'voucher_xtra_service_fee',
    'Order processing fee'                                 : 'order_processing_fee',
    'Biaya pemrosesan pesanan'                             : 'order_processing_fee',
    'EAMS Program service fee'                             : 'eams_program_service_fee',
    'Biaya layanan Program EAMS'                           : 'eams_program_service_fee',
    'Brands Crazy Deals/Flash Sale service fee'            : 'brands_crazy_deals_flash_sale_service_fee',
    'Biaya layanan Brands Crazy Deal/Flash Sale'           : 'brands_crazy_deals_flash_sale_service_fee',
    'Dilayani Tokopedia fee'                               : 'dilayani_tokopedia_fee',
    'Biaya Dilayani Tokopedia'                             : 'dilayani_tokopedia_fee',
    'Dilayani Tokopedia handling fee'                      : 'dilayani_tokopedia_handling_fee',
    'Biaya penanganan Dilayani Tokopedia'                  : 'dilayani_tokopedia_handling_fee',
    'PayLater program fee'                                 : 'paylater_program_fee',
    'Biaya program PayLater'                               : 'paylater_program_fee',
    'Campaign resource fee'                                : 'campaign_resource_fee',
    'Biaya sumber daya campaign'                           : 'campaign_resource_fee',
    'Installation service fee'                             : 'installation_service_fee',
    'Biaya layanan penginstalan'                           : 'installation_service_fee',
    'Article 22 Income Tax withheld'                       : 'article_22_income_tax_withheld',
    'PPh Pasal 22 dipungut'                                : 'article_22_income_tax_withheld',
    'Platform special service fee'                         : 'platform_special_service_fee',
    'Biaya layanan khusus platform'                        : 'platform_special_service_fee',
    'GMV Max ad fee'                                       : 'gmv_max_ad_fee',
    'Biaya iklan GMV Max'                                  : 'gmv_max_ad_fee',
    'GMV Max Coupon'                                       : 'gmv_max_coupon',
    'GMV Max coupon'                                       : 'gmv_max_coupon',
    'Voucher GMV Max'                                      : 'gmv_max_coupon',
    'GMV Max coupon sales tax'                             : 'gmv_max_coupon_sales_tax',
    'Pajak penjualan atas voucher GMV Max'                 : 'gmv_max_coupon_sales_tax',
    'Managed service plan (Sales tax)'                     : 'managed_service_plan_sales_tax',
    'Program layanan terkelola (Pajak penjualan)'          : 'managed_service_plan_sales_tax',
    'Managed service plan (Per order fee)'                 : 'managed_service_plan_per_order_fee',
    'Program layanan terkelola (Biaya per pesanan)'        : 'managed_service_plan_per_order_fee',
    'Ongkir pesanan gagal kirim'                           : 'failed_delivery_shipping_fee',
    'Ongkir pengembalian barang karena kesalahan pembeli'  : 'buyer_fault_return_shipping_fee',
    'Biaya asuransi'                                       : 'insurance_fee',
    'Ajustment amount'                                     : 'ajustment_amount',
    'Jumlah penyesuaian'                                   : 'ajustment_amount',
    'Related order ID'                                     : 'related_order_id',
    'ID pesanan terkait'                                   : 'related_order_id',
    'Shipping fee adjustment'                              : 'shipping_fee_adjustment',
    'Shipping fee compensation'                            : 'shipping_fee_compensation',
    'Chargeback'                                           : 'chargeback',
    'Logistics service fee'                                : 'logistics_service_fee',
    'Biaya layanan logistik'                               : 'logistics_service_fee',
    'Customer service compensation'                        : 'customer_service_compensation',
    'Promotion adjustment'                                 : 'promotion_adjustment',
    'Platform compensation'                                : 'platform_compensation',
    'Platform penalty'                                     : 'platform_penalty',
    'Sample shipping fee'                                  : 'sample_shipping_fee',
    'Logistics reimbursement'                              : 'logistics_reimbursement',
    'Platform reimbursement'                               : 'platform_reimbursement',
    'Deductions incurred by seller'                        : 'deductions_incurred_by_seller',
    'Shipping fee rebate'                                  : 'shipping_fee_rebate',
    'Warehouse service fee'                                : 'warehouse_service_fee',
    'Platform commission adjustment'                       : 'platform_commission_adjustment',
    'Platform commission compensation'                     : 'platform_commission_compensation',
    'Transaction fee adjustment'                           : 'transaction_fee_adjustment',
    'Top up for ads from settled balances'                 : 'top_up_for_ads_from_settled_balances',
    'Campaign Package'                                     : 'campaign_package',
    'Additional Campaign Package'                          : 'additional_campaign_package',
    'GMV Payment for TikTok Ads'                           : 'gmv_payment_for_tiktok_ads',
    'GMV Payment for Promote'                              : 'gmv_payment_for_promote',
    'Shipping insurance compensation'                      : 'shipping_insurance_compensation',
    'Penggantian dana asuransi'                            : 'shipping_insurance_compensation',
    'Other adjustment'                                     : 'other_adjustment',
    'Customer payment'                                     : 'customer_payment',
    'Pembayaran oleh pembeli'                              : 'customer_payment',
    'Customer refund'                                      : 'customer_refund',
    'Pengembalian dana pembeli'                            : 'customer_refund',
    'Seller co-funded voucher discount'                    : 'seller_co_funded_voucher_discount',
    'Diskon voucher yang ditanggung penjual'               : 'seller_co_funded_voucher_discount',
    'Refund of seller co-funded voucher discount'          : 'refund_of_seller_co_funded_voucher_discount',
    'Pengembalian dana diskon voucher yang ditanggung penjual'  : 'refund_of_seller_co_funded_voucher_discount',
    'Platform discounts'                                   : 'platform_discounts',
    'Diskon platform'                                      : 'platform_discounts',
    'Refund of platform discounts'                         : 'refund_of_platform_discounts',
    'Pengembalian dana diskon platform'                    : 'refund_of_platform_discounts',
    'Platform co-funded voucher discounts'                 : 'platform_co_funded_voucher_discounts',
    'Diskon voucher yang ditanggung platform'              : 'platform_co_funded_voucher_discounts',
    'Refund of platform co-funded voucher discounts'       : 'refund_of_platform_co_funded_voucher_discounts',
    'Pengembalian dana diskon voucher yang ditanggung platform' : 'refund_of_platform_co_funded_voucher_discounts',
    'Seller shipping cost discount'                        : 'seller_shipping_cost_discount',
    'Diskon ongkir dari penjual'                           : 'seller_shipping_cost_discount',
    'Estimated package weight (g)'                         : 'estimated_package_weight',
    'Perkiraan berat paket'                                : 'estimated_package_weight',
    'Actual package weight (g)'                            : 'actual_package_weight',
    'Berat paket yang bisa dikenai biaya'                  : 'actual_package_weight',
    'Order Source'                                         : 'order_source',
    'Sumber pesanan'                                       : 'order_source',
    'Shopping center items'                                : 'shopping_center_items',
    'Detail produk terjual'                                : 'shopping_center_items',
}

TIKTOK_REPORT_COLUMN_MAP = {
    'Type'              : 'type',
    'Jenis transaksi'   : 'type',
    'Reference ID'      : 'reference_id',
    'ID referensi'      : 'reference_id',
    'Request time'      : 'request_time',
    'Waktu permintaan'  : 'request_time',
    'Amount'            : 'amount',
    'Total'             : 'amount',
    'Status'            : 'status',
    'Success time'      : 'success_time',
    'Waktu keberhasilan' : 'success_time',
    'Bank account'      : 'bank_account',
    'Rekening bank'     : 'bank_account',
}
