"""Crewdible endpoint registry."""

from __future__ import annotations

from scripts.api.models import EndpointSpec


CREWDIBLE_ENDPOINTS: tuple[EndpointSpec, ...] = (
    EndpointSpec(
        name="accounts_info_warehouses",
        endpoint_group="warehouses",
        endpoint="/accounts/info/warehouses",
        file_prefix="accounts_info_warehouses",
    ),
    EndpointSpec(
        name="warehouses_info_contract",
        endpoint_group="warehouses",
        endpoint="/warehouses/info/contract/{warehouse}",
        file_prefix="warehouses_info_contract",
        path_params=("warehouse",),
    ),
    EndpointSpec(
        name="stock_inbound_lists",
        endpoint_group="stock_inbound",
        endpoint="/stock/inbound/lists/{status}",
        file_prefix="stock_inbound_lists",
        path_params=("status",),
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="stock_inbound_detail",
        endpoint_group="stock_inbound",
        endpoint="/stock/inbound/detail",
        file_prefix="stock_inbound_detail",
        required_params=("inbound",),
    ),
    EndpointSpec(
        name="stock_inbound_shipping_label",
        endpoint_group="stock_inbound",
        endpoint="/stock/inbound/shipping-label",
        file_prefix="stock_inbound_shipping_label",
        required_params=("inbound",),
    ),
    EndpointSpec(
        name="stock_lists_product",
        endpoint_group="stock_warehouse",
        endpoint="/stock/lists/product",
        file_prefix="stock_lists_product",
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="stock_lists_warehouse",
        endpoint_group="stock_warehouse",
        endpoint="/stock/lists/warehouse",
        file_prefix="stock_lists_warehouse",
        required_params=("warehouse",),
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="stock_lists_export",
        endpoint_group="stock_warehouse",
        endpoint="/stock/lists/export",
        file_prefix="stock_lists_export",
        required_params=("warehouse",),
    ),
    EndpointSpec(
        name="stock_mutations_summary",
        endpoint_group="stock_mutations",
        endpoint="/stock/mutations/summary",
        file_prefix="stock_mutations_summary",
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="stock_mutations_history",
        endpoint_group="stock_mutations",
        endpoint="/stock/mutations/history",
        file_prefix="stock_mutations_history",
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="products_get_info",
        endpoint_group="products",
        endpoint="/products/get/info",
        file_prefix="products_get_info",
        required_params=("sku",),
    ),
    EndpointSpec(
        name="products_get_items",
        endpoint_group="products",
        endpoint="/products/get/items",
        file_prefix="products_get_items",
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="products_search",
        endpoint_group="products",
        endpoint="/products/search",
        file_prefix="products_search",
        required_params=("keyword",),
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="logistics_lists_all",
        endpoint_group="logistics",
        endpoint="/logistics/lists/all",
        file_prefix="logistics_lists_all",
    ),
    EndpointSpec(
        name="logistics_lists_outbound",
        endpoint_group="logistics",
        endpoint="/logistics/lists/outbound/{type}",
        file_prefix="logistics_lists_outbound",
        path_params=("type",),
    ),
    EndpointSpec(
        name="logistics_lists_inbound",
        endpoint_group="logistics",
        endpoint="/logistics/lists/inbound/{type}",
        file_prefix="logistics_lists_inbound",
        path_params=("type",),
    ),
    EndpointSpec(
        name="packaging_items",
        endpoint_group="packaging",
        endpoint="/packaging/items",
        file_prefix="packaging_items",
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="order_search_all",
        endpoint_group="order_all",
        endpoint="/order/search/all",
        file_prefix="order_search_all",
        required_params=("query",),
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="order_detail_inv",
        endpoint_group="order_detail",
        endpoint="/order/detail/inv",
        file_prefix="order_detail_inv",
        required_params=("invoice",),
    ),
    EndpointSpec(
        name="order_detail_dropship",
        endpoint_group="order_detail",
        endpoint="/order/detail/dropship",
        file_prefix="order_detail_dropship",
        required_params=("invoice",),
    ),
    EndpointSpec(
        name="order_detail_cod",
        endpoint_group="order_detail",
        endpoint="/order/detail/cod",
        file_prefix="order_detail_cod",
        required_params=("invoice",),
    ),
    EndpointSpec(
        name="order_detail_exit",
        endpoint_group="order_detail",
        endpoint="/order/detail/exit",
        file_prefix="order_detail_exit",
        required_params=("invoice",),
    ),
    EndpointSpec(
        name="order_detail_move",
        endpoint_group="order_detail",
        endpoint="/order/detail/move",
        file_prefix="order_detail_move",
        required_params=("invoice",),
    ),
    EndpointSpec(
        name="order_detail_address",
        endpoint_group="order_detail",
        endpoint="/order/detail/{type}/address",
        file_prefix="order_detail_address",
        path_params=("type",),
        required_params=("invoice",),
    ),
    EndpointSpec(
        name="order_lists_move",
        endpoint_group="order_all",
        endpoint="/order/lists/move/{status}",
        file_prefix="order_lists_move",
        path_params=("status",),
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="order_lists",
        endpoint_group="order_all",
        endpoint="/order/lists/{category}/{status}",
        file_prefix="order_lists",
        path_params=("category", "status"),
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="loadings_get_info",
        endpoint_group="loadings",
        endpoint="/loadings/get/info",
        file_prefix="loadings_get_info",
        required_params=("loading",),
    ),
    EndpointSpec(
        name="loadings_get_item",
        endpoint_group="loadings",
        endpoint="/loadings/get/item/{status}",
        file_prefix="loadings_get_item",
        path_params=("status",),
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="qc_request_items",
        endpoint_group="qc",
        endpoint="/qc/request/items",
        file_prefix="qc_request_items",
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="qc_request_detail",
        endpoint_group="qc",
        endpoint="/qc/request/detail",
        file_prefix="qc_request_detail",
        required_params=("request",),
    ),
    EndpointSpec(
        name="so_request_items",
        endpoint_group="so",
        endpoint="/so/request/items",
        file_prefix="so_request_items",
        pagination_strategy="page_limit",
        default_payload={"page": 1, "limit": 50},
    ),
    EndpointSpec(
        name="so_request_detail",
        endpoint_group="so",
        endpoint="/so/request/detail",
        file_prefix="so_request_detail",
        required_params=("request",),
    ),
)


def get_endpoint_specs(
    *,
    endpoint_group: str | None = None,
    endpoint_name: str | None = None,
) -> list[EndpointSpec]:
    specs = list(CREWDIBLE_ENDPOINTS)
    if endpoint_group:
        specs = [spec for spec in specs if spec.endpoint_group == endpoint_group]
    if endpoint_name:
        specs = [spec for spec in specs if spec.name == endpoint_name]
    return specs
