# src/transform/_maps.py
"""
Semua dictionary mapping untuk proses transform.
Nilai channel_name harus selalu cocok dengan dim_sales_channel.channel_name.
"""

# ── Shopee ─────────────────────────────────────────────────────────────────────
SHOPEE_CHANNEL_MAP = {
    'official':                 'Official',
    'merapi':                   'Merapi Organik',
    'merapiorganik':            'Merapi Organik',
    'merapi organik':           'Merapi Organik',
    'diy':                      'Wellfarm.ID',
    'diy jateng':               'Wellfarm.ID',
    'wellfarm diy':             'Wellfarm.ID',
    'wellfarmdiyjateng':        'Wellfarm.ID',
    'wellfarm.id':              'Wellfarm.ID',
    'porice':                   'Beras Porang Porice',
    'beras porang porice':      'Beras Porang Porice',
    'beras sehat':              'Beras Sehat',
    'berassehat':               'Beras Sehat',
    'bandar organik':           'Bandar Organik',
    'bandarorganik':            'Bandar Organik',
    'bandar organk':            'Bandar Organik',
    'bandar':                   'Bandar Organik',
    'lembah':                   'Lembah Organik Store',
    'lembah organik':           'Lembah Organik Store',
    'lembahorganik':            'Lembah Organik Store',
    'diabetashop':              'Beras Diabeta Shop',
    'diabetasop':               'Beras Diabeta Shop',
    'berasdiabetes':            'Beras Diabeta Shop',
    'beras diabeta shop':       'Beras Diabeta Shop',
    'truly':                    'Truly Organic',
    'truly organik':            'Truly Organic',
    'trulyorganik':             'Truly Organic',
    'merbabu':                  'Merbabu Organik',
    'merbabu organik':          'Merbabu Organik',
    'merbabuorganik':           'Merbabu Organik',
    'merababu':                 'Merbabu Organik',
    'merbau':                   'Merbabu Organik',
    'bromo':                    'Bromo Organik',
    'bromoorganik':             'Bromo Organik',
    'diet':                     'Diet Healthy Corner',
    'diet healthy':             'Diet Healthy Corner',
    'diethealthy':              'Diet Healthy Corner',
    'diet healthy corner':      'Diet Healthy Corner',
    'bogor':                    'Bogor Healthy Store',
    'bogor healthy':            'Bogor Healthy Store',
    'bogorhealthy':             'Bogor Healthy Store',
    'bogorhealthystore':        'Bogor Healthy Store',
    'bogor healhy':             'Bogor Healthy Store',
    'basecamp':                 'Basecamp Organik',
    'basecamporganik':          'Basecamp Organik',
    'basecamp organik':         'Basecamp Organik',
    'owellnes':                 'Owellness',
    'owellness':                'Owellness',
    'sumber organik':           'Sumber Organik Shop',
    'sumber organik shop':      'Sumber Organik Shop',
    'sumberorganikshop':        'Sumber Organik Shop',
    'solo':                     'Solo Organik',
    'solo organik':             'Solo Organik',
    'soloorganik':              'Solo Organik',
    'pusat beras':              'Pusat Beras Berkualitas',
    'pusat beras berkualitas':  'Pusat Beras Berkualitas',
    'pusat beras berkualita':   'Pusat Beras Berkualitas',
    'pusatberasberkualitas':    'Pusat Beras Berkualitas',
    'zona':                     'Zona Pangan Sehat',
    'zona pangan':              'Zona Pangan Sehat',
    'zonapangan':               'Zona Pangan Sehat',
    'zonapangansehat':          'Zona Pangan Sehat',
    'solusi':                   'Solusi Beras Sehat',
    'solusi beras sehat':       'Solusi Beras Sehat',
    'solusi beras seat':        'Solusi Beras Sehat',
    'solusiberassehat':         'Solusi Beras Sehat',
    'sumber pangan':            'Sumber Pangan Pokok',
    'sumber pangan pokok':      'Sumber Pangan Pokok',
    'sumberpanganpokok':        'Sumber Pangan Pokok',
    'porang sachet':            'Porang Sachet Store',
    'porang sachet store':      'Porang Sachet Store',
    'porangsachetstore':        'Porang Sachet Store',
    'porangsachet':             'Porang Sachet Store',
    'indoporang':               'Indo Porang Market',
    'indoporang market':        'Indo Porang Market',
    'organic':                  'Organic Groceries',
    'organic groceries':        'Organic Groceries',
    'organicgroceries':         'Organic Groceries',
    'mekar':                    'Mekar Organik',
    'mekar organik':            'Mekar Organik',
    'mapan':                    'Mapan Organik',
    'mapan organik':            'Mapan Organik',
    'mapanorganik':             'Mapan Organik',
    'mapan oraganik':           'Mapan Organik',
    'medan':                    'Medan Organik',
    'medan organik':            'Medan Organik',
    'medanorganik':             'Medan Organik',
    'berasmedanorganik':        'Beras Medan Organik',
    'beras medan organik':      'Beras Medan Organik',
}

# ── TikTok-Tokopedia ───────────────────────────────────────────────────────────
TIKTOK_CHANNEL_MAP = {
    'wellfarm id':      'Wellfarm ID',
    'wellfarm store':   'Wellfarm Shop',
    'wellfarm shop':    'Wellfarm Shop',
    'pundi':            'Pundi Organik',
    'beras organik id': 'Beras Organik ID',
    'organik id':       'Beras Organik ID',
    'organikid':        'Beras Organik ID',
    'merapi organik':   'Merapi Organik',
    'merapi':           'Merapi Organik',
    'beras sehat':      'Beras Sehat Shop',
    'bromo organik':    'Bromo Organik',
    'bromo':            'Bromo Organik',
    'owellness':        'Owellness',
    'porice':           'Porang Porice',
    'porang porice':    'Porang Porice',
    'diy jateng':       'DIY Jateng',
    'diy':              'DIY Jateng',
    'official':         'Basecamp Organik',
    'basecamp organik': 'Basecamp Organik',
    'basecamp':         'Basecamp Organik',
    'bogor healthy':    'Bogor Healthy Store',
    'bogor':            'Bogor Healthy Store',
}

# ── Lazada ─────────────────────────────────────────────────────────────────────
LAZADA_CHANNEL_MAP = {
    'official':    'Official',
    'merapi':      'Merapi',
    'beras sehat': 'Beras Sehat',
}

# ── Warehouse ──────────────────────────────────────────────────────────────────
SHOPEE_WAREHOUSE_MAP = {
    'amerta warehose':   'Amerta',
    'gudang hb riau':    'Harapan Indah Riau',
    'mavisha storage':   'Mavisha',
    'seller space bo':   'Sellerspace',
    'store n go':        'Store n Go',
    'store n go 1':      'Store n Go',
}

TIKTOK_WAREHOUSE_MAP = {
    'aghitsna':                         'Aghitsna',
    'athena':                           'Athena',
    'athena warehouse':                 'Athena',
    'crewdible kalicari':               'Kalicari',
    'gravitywarehouse wellfarm':        'Gravity',
    'gudang amerta':                    'Amerta',
    'hirota new':                       'Hirota',
    'hirota new fullfilmen':            'Hirota',
    'kapuk muara warehouse':            'Kapuk Muara',
    'malang':                           'Malang Warehouse',
    'mavisa':                           'Mavisha',
    'mavisha storage':                  'Mavisha',
    'mavisha storage jaktim':           'Mavisha',
    'seller space x merapi organik':    'Sellerspace',
    'store n go':                       'Store n Go',
    'stor n go':                        'Store n Go',
}

LAZADA_WAREHOUSE_MAP = {
    'gudang mavisa':   'Mavisha',
    'mavisha storage': 'Mavisha',
}

# ── Shipping ───────────────────────────────────────────────────────────────────
SHOPEE_SHIPPING_MAP = {
    'SPX Hemat':                        16,
    'SPX Standard':                     15,
    'SiCepat REG':                      7,
    'SPX Sameday':                      17,
    'Anteraja Economy':                 12,
    'SPX Instant (Versi Lama)':         18,
    'SPX Instant':                      18,
    'SPX Instant Prioritas':            18,
    'SiCepat Halu':                     9,
    'Anteraja Reguler':                 11,
    'Sicepat Gokil':                    9,
    'ID Express':                       24,
    'JNE Trucking (JTR)':               3,
    'J&T Cargo':                        6,
    'J&T Express':                      4,
    'GrabExpress Sameday':              22,
    'JNE Reguler':                      1,
    'J&T Economy':                      5,
    'GoSend Same Day':                  20,
    'Anteraja Cargo':                   14,
    'Anteraja Sameday':                 13,
    'GrabExpress Instant':              21,
    'GrabExpress Instant (Versi Lama)': 21,
    'GrabExpress Instant Prioritas':    21,
    'Gosend Instant':                   19,
    'GoSend Instant (Versi Lama)':      19,
    'GoSend Instant Prioritas':         19,
    'Ninja Xpress':                     23,
    'JNE YES':                          2,
    'Sicepat BEST':                     8,
    'Sentral Cargo':                    25,
    'Pos Reguler':                      29,
}

TIKTOK_SHIPPING_MAP = {
    ('Anteraja',               'Kargo'):                14,
    ('Anteraja',               'Same day'):             13,
    ('Anteraja',               'Ekonomi'):              12,
    ('AnterAja-MP',            'AnterAja (Regular)'):   11,
    ('Gojek',                  'Instan'):               19,
    ('Gojek',                  'Same day 8 jam'):       20,
    ('Grab',                   'Instan'):               21,
    ('Grab',                   'Same day 8 jam'):       22,
    ('IDX',                    'Pengiriman standar'):   24,
    ('JNE Cargo',              'Kargo'):                3,
    ('JNE Express Standard ID','_'):                    1,
    ('JNE-MP',                 'JNE (Regular)'):        1,
    ('J&T Cargo',              'Kargo'):                6,
    ('J&T Cargo',              'Pengiriman standar'):   6,
    ('J&T Express',            'Pengiriman standar'):   4,
    ('J&T Express',            'Ekonomi'):              5,
    ('J&T-MP',                 'J&T (Regular)'):        4,
    ('Lion Parcel-MP',         '_'):                    26,
    ('NinjaVan Indonesia',     '_'):                    23,
    ('NinjaVan-MP',            '_'):                    23,
    ('Paxel',                  'Same day'):             27,
    ('REX',                    'Kargo'):                28,
    ('SiCepat',                'Kargo'):                10,
    ('SiCepat-MP',             'SiCepat (Regular)'):    7,
}

LAZADA_SHIPPING_MAP = {
    'JNE':        1,
    'JNE JTR':    3,
    'J&T':        4,
    'J&T CARGO':  6,
    'LEX ID':     30,
    'NinjaVanID': 23,
}

# ── Fee columns (unpivot wide→narrow) ─────────────────────────────────────────

TIKTOK_INCOME_FEE_COLS = {
    'seller_co_funded_voucher_discount':                  20,
    'refund_of_seller_co_funded_voucher_discount':        21,
    'platform_discounts':                                 22,
    'refund_of_platform_discounts':                       23,
    'platform_co_funded_voucher_discounts':               24,
    'refund_of_platform_co_funded_voucher_discounts':     25,
    'seller_shipping_cost_discount':                      26,
    'platform_commission_fee':                            27,
    'pre_order_service_fee':                              28,
    'mall_service_fee':                                   29,
    'payment_fee':                                        30,
    'shipping_fee_program_service_fee':                   31,
    'order_processing_fee':                               32,
    'paylater_program_fee':                               33,
    'affiliate_commission':                               34,
    'affiliate_partner_commission':                       35,
    'affiliate_shop_ads_commission':                      36,
    'affiliate_partner_shop_ads_commission':              37,
    'dynamic_commission':                                 38,
    'gmv_max_ad_fee':                                     39,
    'gmv_max_coupon':                                     40,
    'bonus_cashback_service_fee':                         41,
    'live_specials_service_fee':                          42,
    'voucher_xtra_service_fee':                           43,
    'eams_program_service_fee':                           44,
    'brands_crazy_deals_flash_sale_service_fee':          45,
    'campaign_resource_fee':                              46,
    'shipping_cost':                                      47,
    'shipping_costs_passed_on_to_the_logistics_provider': 48,
    'replacement_shipping_fee_passed_on_to_the_customer': 49,
    'exchange_shipping_fee_passed_on_to_the_customer':    50,
    'shipping_cost_borne_by_the_platform':                51,
    'shipping_cost_paid_by_the_customer':                 52,
    'refunded_shipping_cost_paid_by_the_customer':        53,
    'return_shipping_costs_passed_on_to_the_customer':    54,
    'shipping_cost_subsidy':                              55,
    'distance_shipping_fee_from_horizon_plus_program':    56,
    'distance_item_fee_from_horizon_plus_program':        57,
    'dilayani_tokopedia_fee':                             58,
    'dilayani_tokopedia_handling_fee':                    59,
    'installation_service_fee':                           60,
    'platform_special_service_fee':                       61,
    'article_22_income_tax_withheld':                     63,
    'shipping_fee_adjustment':                            64,
    'shipping_fee_compensation':                          65,
    'chargeback':                                         66,
    'customer_service_compensation':                      67,
    'promotion_adjustment':                               68,
    'platform_compensation':                              69,
    'platform_penalty':                                   70,
    'sample_shipping_fee':                                71,
    'logistics_reimbursement':                            72,
    'platform_reimbursement':                             73,
    'deductions_incurred_by_seller':                      74,
    'shipping_fee_rebate':                                75,
    'warehouse_service_fee':                              76,
    'platform_commission_adjustment':                     77,
    'platform_commission_compensation':                   78,
    'transaction_fee_adjustment':                         79,
    'campaign_package':                                   80,
    'additional_campaign_package':                        81,
    'gmv_payment_for_promote':                            82,
    'gmv_payment_for_tiktok_ads':                         83,
    'shipping_insurance_compensation':                    84,
    'other_adjustment':                                   86,
    'top_up_for_ads_from_settled_balances':               87,
}

SHOPEE_INCOME_MAIN_FEE_COLS = {
    'voucher_disponsor_oleh_penjual':                                   88,
    'voucher_co_fund_disponsor_oleh_penjual':                           89,
    'cashback_koin_disponsori_penjual':                                 90,
    'cashback_koin_co_fund_disponsori_penjual':                         91,
    'diskon_produk_dari_shopee':                                        92,
    'promo_gratis_ongkir_dari_penjual':                                 93,
    'gratis_ongkir_dari_shopee':                                        94,
    'diskon_ongkir_ditanggung_jasa_kirim':                              95,
    'biaya_program_hemat_biaya_kirim':                                  96,
    'biaya_administrasi_termasuk_ppn_11':                               97,
    'biaya_layanan':                                                    98,
    'biaya_transaksi':                                                  99,
    'biaya_proses_pesanan':                                            100,
    'premi':                                                           101,
    'biaya_isi_saldo_otomatis_dari_penghasilan':                       103,
    'biaya_komisi_ams':                                                104,
    'biaya_kampanye':                                                  105,
    'ongkir_dibayar_pembeli':                                          111,
    'ongkir_yang_diteruskan_oleh_shopee_ke_jasa_kirim':                112,
    'ongkos_kirim_pengembalian_barang':                                113,
    'kembali_ke_biaya_pengiriman_pengirim':                            114,
    'pengembalian_biaya_kirim':                                        115,
    'bea_masuk_ppn_pph':                                               116,
    'kompensasi':                                                      117,
    'pro_rata_koin_yang_ditukarkan_untuk_pengembalian_barang':         118,
    'pro_rata_voucher_shopee_untuk_pengembalian_barang':               119,
    'pro_rated_bank_payment_channel_promotion_for_return_refund_item': 120,
    'pro_rated_shopee_payment_channel_promotion_for_return_refund_it': 121,
}

TIKTOK_NON_FEE_COLS = frozenset({
    'order_adjustment_id', 'type', 'order_created_time', 'order_settled_time',
    'currency', 'total_settlement_amount', 'total_revenue',
    'subtotal_after_seller_discounts', 'subtotal_before_discounts',
    'seller_discounts', 'refund_subtotal_after_seller_discounts',
    'refund_subtotal_before_seller_discounts', 'refund_of_seller_discounts',
    'total_fees', 'ajustment_amount', 'related_order_id',
    'customer_payment', 'customer_refund', 'estimated_package_weight',
    'actual_package_weight', 'nama_toko', 'source_filename',
    'order_source', 'shopping_center_items',
})

SHOPEE_MAIN_NON_FEE_COLS = frozenset({
    'no', 'no_pesanan', 'no_pengajuan', 'username_pembeli',
    'waktu_pesanan_dibuat', 'metode_pembayaran_pembeli', 'tanggal_dana_dilepaskan',
    'harga_asli_produk', 'total_diskon_produk', 'jumlah_pengembalian_dana_ke_pembeli',
    'total_penghasilan', 'kode_voucher', 'jasa_kirim', 'nama_kurir',
    'pengembalian_dana_ke_pembeli', 'nama_toko', 'source_filename',
})

SHOPEE_SF_MAPPED_FEE_COLS = frozenset({
    'biaya_pembayaran',
    'biaya_layanan_gratis_ongkir_xtra', 'biaya_layanan_gratis_ongkir_xtra_2',
    'biaya_layanan_promo_xtra',
    'biaya_layanan_cashback_xtra', 'biaya_layanan_cashbackxtra',
    'biaya_program_shopee_live_xtra',
    'biaya_campaign_1_1',  'biaya_campaign_2_2',  'biaya_campaign_3_3',
    'biaya_campaign_4_4',  'biaya_campaign_5_5',  'biaya_campaign_6_6',
    'biaya_campaign_7_7',  'biaya_campaign_8_8',  'biaya_campaign_9_9',
    'biaya_campaign_10_10', 'biaya_campaign_11_11', 'biaya_campaign_12_12',
})

SHOPEE_SF_NON_FEE_COLS = frozenset({'no', 'no_pesanan', 'nama_toko', 'source_filename'})

# ── Crewdible ──────────────────────────────────────────────────────────────────
CREWDIBLE_WAREHOUSE_MAP = {
    'crewdible kalicari':           'Kalicari',
    'crewdible gudang solo':        'Gudang Solo',
    'kalicari':                     'Kalicari',
    'gudang solo':                  'Gudang Solo',
    'athena':                       'Athena',
    'athena warehouse':             'Athena',
    'mavisha':                      'Mavisha',
    'mavisha storage':              'Mavisha',
    'mavisha storage jaktim':       'Mavisha',
    'gravity':                      'Gravity',
    'gravitywarehouse wellfarm':    'Gravity',
    'amerta':                       'Amerta',
    'gudang amerta':                'Amerta',
    'store n go':                   'Store n Go',
    'store n go 1':                 'Store n Go',
    'kapuk muara':                  'Kapuk Muara',
    'kapuk muara warehouse':        'Kapuk Muara',
    'aghitsna':                     'Aghitsna',
    'sellerspace':                  'Sellerspace',
    'seller space':                 'Sellerspace',
    'hirota':                       'Hirota',
    'hirota new':                   'Hirota',
    'hd warehouse':                 'HD Warehouse',
    'ar galaxy':                    'AR Galaxy',
    'uju bandung':                  'Uju Bandung',
    'malang':                       'Malang Warehouse',
    'malang warehouse':             'Malang Warehouse',
    'hea':                          'HEA Fullfilment',
    'hea fulfilment':               'HEA Fullfilment',
    'harapan indah':                'Harapan Indah Riau',
    'harapan indah riau':           'Harapan Indah Riau',
    'cd warehouse':                 'CD Warehouse',
    'gudang dc jogja':              'Gudang DC Jogja',
    'basecamp':                     'Gudang DC Jogja',
}

CREWDIBLE_MARKETPLACE_MAP = {
    'shopee':           1,
    'tiktok shop':      2,
    'tiktok':           2,
    'tokopedia':        3,
    'lazada':           4,
    'tiktok-tokopedia': 5,
}

CREWDIBLE_STORE_MAP = {
    'wellfarm':                     'Wellfarm Official',
    'wellfarm official':            'Wellfarm Official',
    'wellfarm id':                  'Wellfarm ID',
    'wellfarm store':               'Wellfarm Store',
    'merapi':                       'Merapi Organik',
    'merapi organik':               'Merapi Organik',
    'diy':                          'Wellfarm DIY Jateng',
    'diy jateng':                   'Wellfarm DIY Jateng',
    'wellfarm diy':                 'Wellfarm DIY Jateng',
    'wellfarm diy jateng':          'Wellfarm DIY Jateng',
    'porice':                       'Porice Official',
    'porice official':              'Porice Official',
    'beras sehat':                  'Beras Sehat',
    'bandar organik':               'Bandar Organik',
    'lembah organik':               'Lembah Organik',
    'diabetashop':                  'Diabetashop',
    'truly organik':                'Truly Organik',
    'truly organic':                'Truly Organik',
    'merbabu organik':              'Merbabu Organik',
    'bromo organik':                'Bromo Organik',
    'bromo':                        'Bromo Organik',
    'diet healthy corner':          'Diet Healthy Corner',
    'bogor healthy store':          'Bogor Healthy Store',
    'basecamp organik':             'Basecamp Organik',
    'owellness':                    'Owellness',
    'owellnes':                     'Owellness',
    'sumber organik':               'Sumber Organik',
    'solo organik':                 'Solo Organik',
    'pusat beras berkualitas':      'Pusat Beras Berkualitas',
    'zona pangan sehat':            'Zona Pangan Sehat',
    'solusi beras sehat':           'Solusi Beras Sehat',
    'sumber pangan pokok':          'Sumber Pangan Pokok',
    'porang sachet store':          'Porang Sachet Store',
    'porang sachet':                'Porang Sachet Store',
    'indo porang market':           'Indo Porang Market',
    'organic groceries':            'Organic Groceries',
    'mekar organik':                'Mekar Organik',
    'mapan organik':                'Mapan Organik',
    'medan organik':                'Medan Organik',
    'pundi organik':                'Pundi Organik',
    'pundi':                        'Pundi Organik',
    'beras organik id':             'Beras Organik ID',
}
